export const interactions = {
  alcohol: {
    caffeine: "warn",
    coke: "unsafe",
    poppers: "warn",
    molly: "unsafe",
    GHB: "deadly",
    K: "deadly",
    acid: "safeDecrease",
    shrooms: "safeDecrease",
    xanax: "deadly",
    viagra: "warn",
  },
  caffeine: {
    coke: "warn",
    poppers: "warn",
    molly: "warn",
    GHB: "warn",
    K: "warn",
    acid: "safeIncrease",
    shrooms: "warn",
    xanax: "safeDecrease",
    viagra: "safeIncrease",
  },
  coke: {
    poppers: "warn",
    molly: "unsafe",
    GHB: "unsafe",
    K: "unsafe",
    acid: "warn",
    shrooms: "warn",
    xanax: "safeDecrease",
    viagra: "deadly",
  },
  poppers: {
    molly: "warn",
    GHB: "deadly",
    K: "warn",
    acid: "safeIncrease",
    shrooms: "safeIncrease",
    xanax: "safeIncrease",
    viagra: "deadly",
  },
  molly: {
    GHB: "warn",
    K: "warn",
    acid: "safeIncrease",
    shrooms: "safeIncrease",
    xanax: "safeDecrease",
    viagra: "warn",
  },
  GHB: {
    K: "deadly",
    acid: "safeDecrease",
    shrooms: "safeDecrease",
    xanax: "unsafe",
    viagra: "unsafe",
  },
  K: {
    acid: "safeIncrease",
    shrooms: "safeIncrease",
    xanax: "unsafe",
    viagra: "safeDecrease",
  },
  acid: {
    shrooms: "safeIncrease",
    xanax: "safeDecrease",
    viagra: "warn",
  },
  shrooms: {
    xanax: "safeDecrease",
    viagra: "unsafe",
  },
  xanax: {
    viagra: "unsafe",
  },
  viagra: {},
};
